### ISSUE TITLE
Re-program and verification

### ISSUE THREAD

**Issue by d82k** [jpleger/hcs301_programming#3]
Hello, 
Can the HCS301 be re-programmed multiple times for updating the key or serial?
Can the content of the HCS301 be read and the information verified (key/serial/etc..)?
Kind regards, 
DK

**Comment by jpleger** [comment]
Should be able to reprogram, but you can't read the written information except for triggering the device and validating the returned data using the keeloq algorithm.

**Comment by jpleger** [comment]
Closing
